name: hyellow_w
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Firebase dependencies - Updated to the latest compatible versions
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  firebase_storage: ^13.0.0
  cloud_functions: ^6.0.0
  firebase_ai: ^3.1.0

  # Functionality dependencies
  http: ^1.2.1
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  photo_manager: ^3.0.0
  #gallery_saver: ^2.3.2
  device_info_plus: ^11.5.0

  file_picker: ^10.2.1
  share_plus: ^11.0.0

  # Other packages
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  uuid: ^4.4.0
  video_player: ^2.8.7
  cached_network_image: ^3.3.1
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.3.1
  marquee: ^2.3.0
  email_validator: ^2.1.17
  google_fonts: ^6.2.1
  dotted_border: ^2.1.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_speed_dial: ^7.0.0
  dropdown_button2: ^2.3.9
  provider: ^6.1.2
  shimmer: ^3.0.0
  timeago: ^3.6.1
  photo_view: ^0.15.0
  intl: ^0.19.0
  flutter_markdown: ^0.7.1
  flutter_cache_manager: ^3.4.1
  lottie: ^2.6.0
  open_filex: ^4.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_bar_icon.png
    - assets/default_profile_image.png
    - assets/chat_bg.jpg